# Generated by Django 2.2.16 on 2021-11-20 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20211118_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='reviews',
        ),
        migrations.AddField(
            model_name='comments',
            name='review',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.Review', verbose_name='review_comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='reviews.Title', verbose_name='title_review'),
        ),
    ]
